# Generated by Django 5.2.1 on 2025-07-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_alter_category_options_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cover_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cover_images')),
            ],
            options={
                'verbose_name': 'Cover Image',
                'verbose_name_plural': 'Cover Images',
            },
        ),
    ]
